### ISSUE TITLE
[docs] Design tokens section docs need review/cleanup

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system#1146]
### Description

We need to clean up the design tokens section on ux dot. I included a content doc and the location of the images on Dropbox.

I don't think we need search on every page, so what do you think about putting it on one page only with all design tokens in a list?

### Acceptance Criteria

- [X] Design done
- [ ] Development done

### Link to design doc

https://xd.adobe.com/view/e26f0898-9926-4577-92f0-bb3bb122af9a-b73c/

### Other resources

Content doc: https://docs.google.com/document/d/1RQMGHi6GF8EtJ-tI4psI1BgUmkK9DmyMcJMWFggTG1U/edit
Images: https://www.dropbox.com/sh/009wow69ose1tko/AAB0Bu8va6Rwe_tjrME4CfM1a?dl=0

**Comment by hellogreg** [comment]
@bennypowers You mentioned wanting some clarification on what's being asked for here. @coreyvickery told me that dropping the images in would be one thing to get started on. 

Any further questions or recommendations on how else to approach this?

**Comment by coreyvickery** [comment]
@bennypowers Here are some small updates I discussed with Greg.

Are we still thinking the demo website is the source of truth and that info should propagate to ux dot? If I can help with making lots of edits to those pages first, let me know. I know that the demo website and my XD are not 1:1 yet; that is on me because I would like there to be a specific order and design of things per page. Maybe this can be a separate issue or even a workshop or something. I would also like to revisit the styling of the tables and disclosure that reveals more info like with color values.

I think we can at least start with these edits. Feel free to push back on anything if it pertains to the demo website work I described above.

### Global
- [ ] Pages in left menu nav not in alphabetical order
- [ ] Can we add an `All design tokens` page right now or should we do that later?
- [ ] Once we add an `All design tokens` page, I would like it to be the only page with search
- [ ] Add correct ux dot footer
- [ ] Apply new section padding values that we made to other Element pages
- [ ] The `Copy to clipboard` button seems to be missing or the functionality isn't working
- [ ] I don't think we need the `Top` anchor links because we have that big red button in the bottom right corner (but I understand they come from the demo website)

### Overview page
- [ ] Ensure content and order is the same as [my XD](https://xd.adobe.com/view/e26f0898-9926-4577-92f0-bb3bb122af9a-b73c/) and [content doc](https://docs.google.com/document/d/1RQMGHi6GF8EtJ-tI4psI1BgUmkK9DmyMcJMWFggTG1U/edit)
- [ ] Add [images](https://www.dropbox.com/sh/009wow69ose1tko/AAB0Bu8va6Rwe_tjrME4CfM1a?dl=0) to containers
- [ ] Under the `Types of tokens` h1, switch the gray block styling to `rh-code-block`

Always up for a meeting of any length if it makes things any easier for you. :)

**Comment by bennypowers** [comment]
Thanks @coreyvickery for writing these items up, it's very helpful to get these 
specific, actionable cues from design 🙌 Let me split the response into two 
areas, starting with some principles and then addressing the practical steps.

## Tokens vs. page design

<details><summary>Click to expand my manifesto :laughing: </summary>


> website is the source of truth  
> demo website and my XD are not 1:1 yet

Tokens and categories descriptions should be documented *in the tokens repo*. 
ux-dot isn't and won't be the only place where these descriptions and summaries 
are useful. Consider for example a WYSIWYG page builder a developer's text 
editor, or a larger cross-org token catalogue, etc. Just like we provide 
documentation on our custom elements to developers which is displayed both on 
our ux-dot docs pages as well as in-situ, so to we should make our tokens as 
easy to understand and use in as many situations as possible.

<figure>
  <img width="1037" alt="" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1466420/dc0c1102-3115-48e7-a256-2cb066c46df7">
  <figcaption>

  VSCode screenshot displaying a tooltip for the pf-button element.
  The tooltip shows the inline JSDoc in pf-button.ts.
  This same documentation appears in the custom-elements manifest,
  and from there is displayed on [patternflyelements.org](https://patternflyelements.org/components/button)

  </figcaption>
</figure>

The best means we have at our disposal to achieve this is to follow a 
materially-honest approach to documentation: describing design system members 
in-situ with as few assumptions about display and use case as possible. With 
that in mind, neither ux-dot _nor_ the demo site should be considered a source 
of truth for anything - the tokens themselves are and *must be* the only source 
of truth here, and the websites, tools, whatsoever which advertise our tokens 
should reflect the tokens as transparently as possible.

In order to present the token pages according to the XD file designs, we had to 
hack around the actual structure of the tokens. What I mean by this is that the 
tokens have their own nested structure with top level categories. As you can 
see, this does not map to the tokens page categories, which were implemented 
using pixels-in-the-xd as the source of truth:

<figure>
  <table>
    <tr>
      <td colspan=2>
        <img width="851" alt="" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1466420/19a3ce27-a0ce-4ebe-a94e-be85a2319ecf">
      </td>
      <td colspan=1>
        <img width="1220" alt="" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1466420/ec570b0f-1fa5-41c3-b3df-a70e3c2865fa">
      </td>
    </tr>
  </table>
  <figcaption>Left: Neovim screenshot displaying the top-level properties of the rhds.tokens.json file.</figcaption>
  <figcaption>Right: Chrome screenshot displaying the tokens overview page, with token categories in the left nav which do not reflect the top-level categories from rhds.tokens.json</figcaption>
</figure>

Tokens are **data**. Whenever we work with the tokens, whether to update them, 
document them, or use them, we ought to keep that in mind. Whenever we discuss 
them, the conversation should put the data in the center, and any visual aids 
used should be understood as such. Changes to the tokens themselves and their metadata (including 
documentation) should be discussed *only* in terms of tokens, i.e. of data. This 
includes things like:
- token names
- token categories
- category structure and nesting
- token and category ordering
- token and category documentation (insofar as those docs relate directly and 
only to the tokens themselves, so excluding docs content which is only relevant 
to specific websites or tools)

Prior discussion 
[here](https://github.com/RedHat-UX/red-hat-design-system/issues/359#issuecomment-1177734201), 
[here](https://github.com/RedHat-UX/red-hat-design-tokens/issues/34), maybe elsewhere. 

Changes to the 
design-of-the-page-which-displays-the-tokens-as-documentation-for-implementers 
would be a separate, secondary, subsidiary discussion. How would that look in 
practice? XD/Figma files would always be considered as mockups / wireframes with 
regards to the token data and structure they present. Wherever there exists a 
conflict between token structure and data in the yaml files and some title or 
value in the mockups, code wins - every time.

Where XD/Figma *does* come in to its own is for designing molecules or organs 
(to borrow terminology from atomic design) for pages on ux-dot (or other 
projects). In other words pixels-in-an-xd-file always wins when it comes to 
questions like "how do we display a group of spacer tokens on the docs page in 
ux-dot", or "should we use sentence case or title case to display this 
dash-cased category name?". What that page or category is called or exactly 
which token names or values are displayed there would *not* be determined via XD 
mockup, but only *from the data*. In extreme cases where there is a compelling 
reason to deviate from the tokens structure in on a docs page, we can do that 
(as we've already done on ux-dot), but those decisions should be taken soberly 
and with good reason, knowing that we're breaking user's expectations.

The XD designs for those molecules and organs would be filed under their host 
projects, not under tokens. Why? because 
how-the-tokens-are-displayed-to-implementers-on-ux-dot is a *ux-dot* problem, 
not a *tokens* problem. Extra content which is only relevant to ux-dot can be 
added to the tokens pages on ux-dot, by slotting that extra content into the 
shortcode which renders the descriptions. This is exactly how we handle element 
documentation, just that the tokens are in a separate repo. 

Adopting this kind of materially-honest design approach to managing our tokens 
would benefit everyone: system producers, designers, developers, and downstream 
users. To be clear: **designers will need to spend more time editing text files 
and less time editing xd files and google docs**. In exchange for that 
(relatively minor change to designer workflows), designers will save time for 
themselves and others, develop empathy for users, gain skills, and ultimately 
deliver a more resiliant, holistic system.

</details>

Thanks for reading all of the above. So with that massive wall of text in mind let's review the line items :D

-----

## Line items

### Global

> Pages in left menu nav not in alphabetical order

Not a huge problem to fix this on the website, but again - you'll notice that 
the tokens themselves are not in order, so this would be better addressed there.

> Can we add an All design tokens page right now or should we do that later?

I'm concerned about duplicating content - there should only be one canonical URL 
for a token on ux-dot.

> Once we add an All design tokens page, I would like it to be the only page 
> with search

This would be a huge hit to usability. Recall that we discussed a few times that 
searching the entire token collection is a showstopper.

> Add correct ux dot footer  
> Apply new section padding values that we made to other Element pages  
> The Copy to clipboard button seems to be missing or the functionality isn't 
> working  
> I don't think we need the Top anchor links because we have that big red button 
> in the bottom right corner (but I understand they come from the demo website)  

Fixing these should be straightforward


### Overview page

> Ensure content and order is the same as [my 
XD](https://xd.adobe.com/view/e26f0898-9926-4577-92f0-bb3bb122af9a-b73c/) and 
[content 
doc](https://docs.google.com/document/d/1RQMGHi6GF8EtJ-tI4psI1BgUmkK9DmyMcJMWFggTG1U/edit)  

See above - when it comes to token content and order - why not go to the source?

> Add 
[images](https://www.dropbox.com/sh/009wow69ose1tko/AAB0Bu8va6Rwe_tjrME4CfM1a?dl=0) 
to containers

I think the listing images here are a gray area. We have received requests in 
the past to provide imagery / iconography for elements inside of wysiwyg 
consumers, so that's an argument for putting them in the tokens repo. OTOH, this 
is arguably a ux-dot-only kind of thing. I'm good either way, as long as we take 
an informed decision based on what's best for the system, rather than basing it 
primarily on "is this page pixel-perfect".

> Under the Types of tokens h1, switch the gray block styling to rh-code-block  

should be a straightforward fix - the content on this page is mostly what could 
reasonably be classify as "ux-dot only", since it relates in broad strokes using 
long-form text to general design system usage.

**Comment by coreyvickery** [comment]
@bennypowers Can we move forward on some of these straightforward fixes? It would be so great if the website looked as nice as possible come demo time on Wednesday. We can address my other points later.

- [ ] Add correct ux dot footer to each page
- [ ] Apply new section padding values that we made to other Element pages
- [ ] The `Copy to clipboard button` seems to be missing or the functionality isn't working properly
- [ ] I don't think we need the Top anchor links because we have that big red button in the bottom right corner (but I understand they're ported from the demo website automatically)
- [ ] Add images to containers on the `Overview` page
- [ ] Under the `Types of tokens` h1, switch the gray block styling to `rh-code-block`

For this one, let's just make sure the `Overview` page has the right copy.

- [ ] Ensure content and order is the same as my XD and content doc

**Comment by bennypowers** [comment]
in the overview page google doc, it's incorrect to replace "semantic tokens" with "alias tokens"

"semantic tokens" is, well, a semantic label - it conveys what it means for a token to be included in that category. "alias tokens" describes a technique - it conveys that this token name was created using the aliasing features of the style-dictionary library. Which of those two is more useful to designers an implementers?

**Comment by bennypowers** [comment]
The feedback sections rely on #1129
