### ISSUE TITLE
[epic] Design kit migration to Figma

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1171]
Placeholder issue for tracking on the Figma migration of our design kits.

- [x] Discovery on workspace structure with DPO
- [x] Migrate "styles"
- [x] Migrate components

**Comment by bennypowers** [comment]
it's worth investigating whether we can take the custom elements manifest as input and generate a figma plugin for our existing elements, so that the design kit would be a 1:1 representation of our library.

one could also imagine some kind of pattern manifest which would do the same with larger design patterns...

**Comment by coreyvickery** [comment]
@markcaron This can probably be closed.
