### ISSUE TITLE
[bug] rh-card public css property to modify background color

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1198]
Currently the `rh-card` does not provide a public css property to modify background color `--rh-card-background-color`.  This feature would support to proposed changes in https://github.com/RedHat-UX/red-hat-design-system/pull/1188

**Comment by bennypowers** [comment]
duplicating comments from the PR, for design review:

Before we merge this, it's worth considering weather it would be wiser to advise users to change the surface color tokens for a given card or class of cards, rather than providing an overriding background variable.

My reasoning is as follows: if we expose the background color variable to users, then users who wish to implement for example a dark background will skip the use of our color context system all together. That is likely to lead to maintenance difficulties, feature creep, and design and accessibility violations.

On the other hand, if we advise users who wish to apply a custom background to explicitly change the surface token values for a given card or class of cards, then they will have to explicitly participate in the context system. Because the context surface tokens have the words "on light" and "on dark" in their names, the user will be subtly encouraged to provide values for both theme variants.

This would have the added advantage of inheriting the provided values to the card's context-consuming children e.g. accordions, which in most cases would be desirable, and could be explicitly opted out of with a child selector

**Comment by brianferry** [comment]
Added docs to help developers customize background color through css tokens.  Can be seen at the bottom of the page here https://deploy-preview-1200--red-hat-design-system.netlify.app/patterns/card/
