### ISSUE TITLE
[feat] Create `<rh-skip-link>`

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1227]
Create a Skip Nav element following [best practices](https://webaim.org/techniques/skipnav/).

**Comment by marionnegp** [comment]
First draft of the skip nav:

![Image](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/9701d61d-e250-4812-bcfb-00d0582ef3f4)

@nikkimk @hellogreg, I have a couple questions about the expected interaction.
- What is the typical keyboard command to activate the skip nav? When I hit `enter` to activate redhat.com's skip nav, the URL changed to `https://www.redhat.com/en#rh-main-content` in the browser, but I still had to tab through the nav.
- Should the site scroll down to the main content? W3C does this, but other sites don't seem to.

**Comment by hellogreg** [comment]
@marionnegp There's currently a bug with the current RHDC skip nav, which is why it's not working. As you wrote, the link has an `href` of `#rh-main-content`, but the div with the `main` role on it has an `id` of `rhb-main-content`. (I know DXFED is aware of this, but I'm going to double-check and see if they've made an issue for it.)

Anyway, you're right in thinking that pressing `enter` should skip the sitewide-repeated content and typically point to the main content. The link `href` just needs to match the `id` of that destination element!

**Comment by marionnegp** [comment]
@hellogreg @nikkimk, could you take a look at a [design draft](https://www.figma.com/file/Xoo1c8M7r5w1XUBzXMDVWp/Skip-nav-(WIP)?type=design&node-id=769%3A3926&mode=design&t=702X3evLXkKeCwkw-1) and [prototype](https://www.figma.com/proto/Xoo1c8M7r5w1XUBzXMDVWp/Skip-nav-(WIP)?page-id=4%3A7073&type=design&node-id=707-12314&viewport=-678%2C388%2C0.5&t=gYP9uRP8bDqMH2wj-1&scaling=min-zoom&starting-point-node-id=707%3A12314&mode=design) of `<rh-skip-nav>`?

In the prototype, you might have to go to `Options` in the top right corner and and uncheck `Show Figma UI` to see the skip nav. After that, you can hit `Tab` to activate skip nav. Hitting `Enter` once will hide the skip nav, and hitting `Enter` a second time should scroll you down a bit to the hero. The need to hit `Enter` twice, instead of once, is due to some prototyping limitations (probably on my part, not Figma's), but I wanted to see what you thought about scrolling down to the main content.

**Comment by hellogreg** [comment]
Design is looking good! One thing to consider is disabling the animations if a user prefers reduced motion (e.g., via a `@media (prefers-reduced-motion)` query).

**Comment by markcaron** [comment]
Renaming to Skip Link / `<rh-skip-link>`

**Comment by marionnegp** [comment]
[Design](https://www.figma.com/file/Xoo1c8M7r5w1XUBzXMDVWp/Skip-link?type=design&node-id=4%3A7073&mode=design&t=KeBj00vc7HjevYYW-1) was approved at Design Leads Sync.

**Comment by marionnegp** [comment]
@coreyvickery, could you review the [skip link docs](https://docs.google.com/document/d/14KCwCyhiIel4zV-fryYH0sYR5vYXaQjv2CSlBkGuqLw/edit?usp=sharing) and let me know if there's something else I should include? It's in a Google doc for now.

**Comment by zeroedin** [comment]
Moved this over to Chansey, I don't think there is opportunity to get it coded reviewed and out the door by end of the month.

**Comment by marionnegp** [comment]
@nikkimk @hellogreg, for a page with a secondary nav, like the [RHEL product page](https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux), should the skip link skip both the primary and secondary navs to get to the main content? I noticed that the current skip link on RHDC doesn't skip secondary nav. I'd like to clarify that in the skip link docs.

**Comment by nikkimk** [comment]
@marionnegp it should skip to main content

**Comment by hellogreg** [comment]
@marionnegp What Nikki said. Because that secondary nav is repeated on multiple pages (albeit not so many as the primary nav), it would be best to skip past it to the page-specific content. 

In this case, I'd say it's not the skip link itself that's wrong, but that it was wrong to put the nav in the "main" section.
