### ISSUE TITLE
[bug] `<rh-card>`: incorrect spacing between header and paragraphs

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1384]
Note: Will be true after #1380 merges

![Screenshot 2023-12-13 at 4 59 50 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/704a2bb3-71a7-43e2-8355-7b40a27b9f39)

https://deploy-preview-1380--red-hat-design-system.netlify.app/elements/card/demo/variants/ 

Per the design spec we should only have 32px here. However we have 32px margin on `#body` + 16px margin on the `<p>`.

**Comment by zeroedin** [comment]
Related future state css: https://developer.apple.com/videos/play/wwdc2023/10121/?time=238

**Comment by bennypowers** [comment]
it's not clear to me that this can be done from the shadow root.
- there's no `:first-of-type-in-slot` pseudo class, 
- we can't `::slotted(* + p:first-of-type)` because complex selectors aren't allowed
- we can't `:first-child`, because what if the heading is the first child?
- we can't `:first-of-type`, because the `p` that comes after the body image is the first of type


we could add a special slot for the logo image, but i'm preeeeetty sure that's not a proper solution (too specific)

or we could say "this is a pattern-level issue" i.e. require light-dom css

**Comment by zeroedin** [comment]
> it's not clear to me that this can be done from the shadow root.

This was my findings, unfortunately just no way of doing it given complex selectors not being allowed.
