### ISSUE TITLE
[feat] `<rh-breadcrumbs>` element

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1458]
We need a Breadcrumb component for use across applications and websites.

The good news is that it seems we have a very closely aligned pattern across PatternFly and our web properties already. We will need to have a design spec created for documentation and made available in Figma.

### Steps

- [x] Design spec
- [x] Develop web component

### Resources

- **Related:** https://github.com/patternfly/patternfly-elements/issues/2688
- [CSS chevron approach](https://github.com/patternfly/patternfly-elements/issues/2688#issuecomment-1908505604)
- [PF Breadcrumb spec](https://www.patternfly.org/components/breadcrumb)
- [RHDC breadcrumbs](https://www.redhat.com/en/topics/linux/whats-the-best-linux-distro-for-you)
- [Portal breadcrumbs](https://access.redhat.com/announcements/7048457)

### Breadcrumb best practice

From [WAI's breadcrumb pattern](https://www.w3.org/WAI/ARIA/apg/patterns/breadcrumb/examples/breadcrumb/):
```
<nav aria-label="Breadcrumb" class="breadcrumb">
  <ol>
    <li>
      <a href="../../../..">
        WAI-ARIA Authoring Practices Guide (APG)
      </a>
    </li>
    <li>
      <a href="../../../">
        Patterns
      </a>
    </li>
    <li>
      <a href="../../">
        Breadcrumb Pattern
      </a>
    </li>
    <li>
      <a href="" aria-current="page">
        Breadcrumb Example
      </a>
    </li>
  </ol>
</nav>
```

**Comment by markcaron** [comment]
Worth discussing: should we have a standard version and one with lighter gray chevrons (to lessen the visual noise on long form content)?

PF's design:
<img width="494" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/83a3b5ae-a96e-4036-8a14-7a61240653dc">

- Color: `#151515`

Use on the Portal:
<img width="722" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/c4ca595c-ca72-4c62-8fe4-aee0b226b35c">

- Color: `#8a8d8d` —> which should be `#707070` (`--rh-color-gray-50`)

**Comment by adamjohnson** [comment]
[Figma Design Spec](https://www.figma.com/file/j7Rjo2W6PLloxOSXQOpll0/Red-Hat-Design-System-library?type=design&node-id=232%3A19495&mode=dev) for `<rh-breadcrumbs>` is available.

**Comment by wesleymiles** [comment]
Wondering if this one will have guidance for mobile. For example, truncating works when there aren't too many levels like [resource pages on WWW](https://www.redhat.com/en/resources/self-managed-openshift-sizing-subscription-guide), but when there are more levels it would be useful to keep them and maybe have them wrap? (see screenshot) ![Screenshot 15](https://github.com/RedHat-UX/red-hat-design-system/assets/613815/14501212-0738-42a1-8a0a-ed3125eeccca)

Or even if we should keep them on mobile or not. [Customer portal](https://access.redhat.com/labsinfo/osdfrc/) drops theirs.

**Comment by adamjohnson** [comment]
@coreyvickery: do you have guidance for breadcrumbs on mobile?

Generally, I think having the text wrap is standard for most orgs.

**Comment by coreyvickery** [comment]
@adamjohnson Or we could try another approach similar to IBM Carbon where they are breaking each step at a given container size.

What do you think would be best?

**Comment by adamjohnson** [comment]
> Or we could try another approach similar to IBM Carbon where they are breaking each step at a given container size.

Wrapping is fine.

> I would avoid having the > icon at the beginning of a line if we can.

Can do.

Note: the [design spec](https://www.figma.com/file/j7Rjo2W6PLloxOSXQOpll0/Red-Hat-Design-System-library?type=design&node-id=232%3A19495&mode=dev) truncates the final breadcrumb item if it's over 27 characters.

```
Home > About > Longer Breadcrumb Item Righ...
```

Would you want "Home"/"About" to truncate if they are longer as well?

**Comment by coreyvickery** [comment]
@adamjohnson No, I think the previous steps should be visible.

I am fine with the last step being truncated because the headline is literally right below.

<img width="363" alt="Screenshot 2024-04-19 at 10 10 01 AM" src="https://github.com/RedHat-UX/red-hat-design-system/assets/45767595/15502f58-f5d9-4570-8dfd-3c0f0265c2f3">

Instead of the above, I would think it would look like this:

> Topics > Application modernization >
> What is Java application moderniz ...

Maybe two lines max and then truncation no matter what.

**Comment by wesleymiles** [comment]
> Maybe two lines max and then truncation no matter what.

for longer paths, i wouldn't want to only limit them to two lines

also, if it hasn't been added yet... would be nice to have guidance around how far back to have the path go, for example all the way to "home," and placement / alignment of breadcrumbs on the page -- they're all over the place now

**Comment by markcaron** [comment]
We could approach it like Google Drive's breadcrumbs. They use `text-overflow: ellipsis` on the links to visually truncate rather than actually truncate:
<img width="298" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/da410b6b-fcc1-4dfd-bd4f-1bf99aae2dad">

And when it nests too deep, it uses a single ellipses to represent more than one level. Clicking the ellipses takes you to whichever "directory" / "link" is the deeper child.
<img width="295" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/dc24834d-b965-4096-af46-8fe8a6f5fed0">

**Comment by adamjohnson** [comment]
## WIP Deploy Preview links:

I wanted to put these WIP Breadcrumb deploy preview links here so that people can see what this looks like now:

* [Basic Demo](https://deploy-preview-1535--red-hat-design-system.netlify.app/elements/breadcrumb/demo/)
* [Color Context](https://deploy-preview-1535--red-hat-design-system.netlify.app/elements/breadcrumb/demo/color-context/)
* [Last item not linked](https://deploy-preview-1535--red-hat-design-system.netlify.app/elements/breadcrumb/demo/last-no-link/)
* [WIP Deploy Preview Docs](https://deploy-preview-1535--red-hat-design-system.netlify.app/elements/breadcrumb/) (still lots to do here!)

The only truncation happening at the moment is on the current page when it's below 992px. The breadcrumbs `<ol>` will wrap beyond two lines. Users can modify margin, padding, background colors etc. as needed since this component uses lightdom.

## Other libraries:

Here's breadcrumb component examples from other WC libraries that don't truncate and just wrap text:

* [Duet](https://www.duetds.com/components/examples/breadcrumbs/)
* [Shoelace](https://shoelace.style/components/breadcrumb)
* [Carbon](https://carbondesignsystem.com/components/breadcrumb/usage/) (wraps early!)
* [Fast](https://explore.fast.design/components/fast-breadcrumb)

Looking at Mark's examples (above), that pattern is interesting from a design and engineering point of view; however, I'm not sure how useful that is to the user since, at smaller viewports, you only get 1-2 letters of a word/words. 

Atlassian has [an interesting take](https://atlassian.design/components/breadcrumbs/examples) on breadcrumbs, which is somewhat similar to [Patternfly](https://www.patternfly.org/components/breadcrumb/). I personally like Atlassian's implementation better, but YMMV.

## Proposed solutions

With this in mind, here's the solutions that have been proposed:

1. Wrap, little/no truncation
1. Wrap, truncate longer links (not just the last link)
1. Limit breadcrumbs to two lines, fully truncate

My vote would be to go with option one or two, but am open to other ideas.

**Comment by coreyvickery** [comment]
@adamjohnson @wesleymiles Thanks for your input, we can show more lines on mobile.

Funny about that Atlassian link, I was typing this last night.

What is the longest path you have seen? Would we ever expect to see something like six links or something? Should we set a  link number limit before truncation? Something like this:

> Home > Link 1 > ... > Link 5 > Link 6

Or even truncate the Home link:

> ... > Link 4 > Link 5 > Link 6

**Comment by wesleymiles** [comment]
> What is the longest path you have seen? 

- for now, this is as long as docs gets: Home / Products / OpenShift Container Platform / 4.15 / Edge computing
- here's a similarly sized one on WWW: Home / Products / Red Hat OpenShift / Red Hat OpenShift Service on AWS / Learn

also like atlassian's solution. could we set auto-collapse based based on the # of lines? or maybe that's what you mean with your proposal #3 @adamjohnson.

**Comment by coreyvickery** [comment]
@adamjohnson @wesleymiles I'm going to start a separate Figma file to explore creating more design options. I'm really hoping this can be included in the `Charmander` release.

**Comment by adamjohnson** [comment]
I'm prototyping the Atlassian solution now. Would love to see what you come up with, Corey.

**Comment by coreyvickery** [comment]
@adamjohnson Here are some more explorations and specs.

https://www.figma.com/proto/FSkPCjWTWK63QfSnX8rChZ/rh-breadcrumb?page-id=1%3A3&type=design&node-id=1-218&viewport=122%2C139%2C1&t=AmmdkOlWBdRh2fWu-1&scaling=min-zoom

**Comment by coreyvickery** [comment]
@adamjohnson Very small updates.

[Dev Mode link](https://www.figma.com/file/j7Rjo2W6PLloxOSXQOpll0/Red-Hat-Design-System-library?type=design&node-id=232%3A19627&mode=dev)

## Light theme

### `Default` variant
- Link text = `blue-50`
- Caret = `gray-95`
- Active page text = `gray-95`

### `Subtle` variant
- Link text = `blue-50`
- Caret = `gray-50`
- Active page text = `gray-60`

## Dark theme

### `Default` variant
- Link text = `blue-30`
- Caret = `white`
- Active page text = `white`

### `Subtle` variant
- Link text = `blue-30`
- Caret = `gray-40`
- Active page text = `gray-30`

**Comment by coreyvickery** [comment]
@adamjohnson Hover colors in case you need them.

## Light theme
- Link text = `blue-70`

## Dark theme
- Link text = `blue-20`

**Comment by markcaron** [comment]
Looking at the [Figma mockup](https://www.figma.com/proto/FSkPCjWTWK63QfSnX8rChZ/rh-breadcrumb?page-id=1%3A3&type=design&node-id=1-218&viewport=122%2C139%2C1&t=AmmdkOlWBdRh2fWu-1&scaling=min-zoom), I'm thinking we should get out an MVP following the "Responsive approach 1".

If we can get "Responsive approach 2" working in the future with a container controller / query, that would be ideal, and we could upgrade to that in a future version.

**Comment by coreyvickery** [comment]
@adamjohnson How's it going with this?

**Comment by adamjohnson** [comment]
> @adamjohnson How's it going with this?

Check out the DP at https://github.com/RedHat-UX/red-hat-design-system/pull/1535/ 👍

**Comment by marionnegp** [comment]
@coreyvickery (and @adamjohnson if you have time), here's a mock up of the [breadcrumb docs](https://www.figma.com/proto/ViSwbxaNaJm4246xaapzJO/Element---Breadcrumbs?node-id=0-1&t=ZVFDlQN4MxSrSm40-1). Let me know if you see anything that should be included, removed, or edited!
