### ISSUE TITLE
[feat] New Figma component for portal navigation

### ISSUE THREAD

**Issue by littledezine** [RedHat-UX/red-hat-design-system#1555]
Please create a new element for the Figma design library that represents the main navigation on the Red Hat Customer Portal (access.redhat.com). 

The component should provide variations for desktop, tablet, and mobile views in both authenticated and unauthenticated states. Refer to the attached screenshots for reference. 
![Desktop unauthenticated](https://github.com/RedHat-UX/red-hat-design-system/assets/163207173/3d61f9f2-0090-42b9-8fc4-e78266d49421)
![Desktop authenticated](https://github.com/RedHat-UX/red-hat-design-system/assets/163207173/c0a21cff-8405-4f3f-a6bb-22001d27c9fd)
![Tablet unauthenticated](https://github.com/RedHat-UX/red-hat-design-system/assets/163207173/e04e2266-885b-4b56-8b56-6fbc0d6b78a4)
![Tablet authenticated](https://github.com/RedHat-UX/red-hat-design-system/assets/163207173/952d341a-67f8-44e7-a5c8-8fa4d468d5bc)
![Mobile unauthenticated](https://github.com/RedHat-UX/red-hat-design-system/assets/163207173/f0888101-8fa6-43af-99a2-aca49369677b)
![Mobile authenticated](https://github.com/RedHat-UX/red-hat-design-system/assets/163207173/cc45b839-ad7f-4a2b-b920-89e403d8b646)

**Comment by coreyvickery** [comment]
@littledezine Hey Cheryl, I have added the following Customer Portal navigation components to the Figma library. The `Header navigation` component is the `Universal navigation` and `Primary navigation` components stacked on top of each other. If you want to know the story of these names, I can tell you somewhere else.

## Header navigation
<img width="1680" alt="--Navigation - header" src="https://github.com/RedHat-UX/red-hat-design-system/assets/45767595/3fa772d6-280e-4a35-8cf7-41037328df03">

### Viewport sizes
- `Desktop, large (1680px)`
- `Desktop, medium (1440px)`
- `Desktop, small (1200px)`
- `Tablet, large (992px)`
- `Tablet, small (768px)`
- `Phone, large (576px)`

(Note: `Phone, small (360px)` and `Phone, extra small (320px)` are not included because they degrade to the `Primary navigation` component because of the lack of space.)

- - -

## Universal navigation
<img width="1680" alt="--Navigation - universal" src="https://github.com/RedHat-UX/red-hat-design-system/assets/45767595/98346db0-9d9a-424a-a7a7-b8fbdb6bec14">

### Viewport sizes
- `Desktop, large (1680px)`
- `Desktop, medium (1440px)`
- `Desktop, small (1200px)`
- `Tablet, large (992px)`
- `Tablet, small (768px)`
- `Phone, large (576px)`

(Note: `Phone, small (360px)` and `Phone, extra small (320px)` are not included because they degrade to the `Primary navigation` component because of the lack of space.)

- - -

## Primary navigation

### Logged out
<img width="1680" alt="--Navigation - primary logged out" src="https://github.com/RedHat-UX/red-hat-design-system/assets/45767595/95545b6b-5c57-493d-97b4-0128058da171">

### Logged in
<img width="1680" alt="--Navigation - primary logged in" src="https://github.com/RedHat-UX/red-hat-design-system/assets/45767595/976ac3f0-6e03-4c98-b0ea-ddc4840c78f9">

(Note: The avatar in the `Logged in` state is a slightly newer version of `rh-avatar`. I updated the design very slightly to match `pf-avatar` in PatternFly 6. This update has not been coded yet, but the design is current and aligns to PatternFly 6.)

### Viewport sizes
- `Desktop, large (1680px)`
- `Desktop, medium (1440px)`
- `Desktop, small (1200px)`
- `Tablet, large (992px)`
- `Tablet, small (768px)`
- `Phone, large (576px)`
- `Phone, small (360px)`
- `Phone, extra small (320px)` - accessibility testing requirement

cc @marionnegp

**Comment by littledezine** [comment]
Thank you @coreyvickery
