### ISSUE TITLE
[bug] Announcement personalization pattern - Vertically center default CTA

### ISSUE THREAD

**Issue by dustinmazon** [RedHat-UX/red-hat-design-system#1617]
### Describe the bug

The CTA in the announcement personalization pattern on desktop sizes does not vertically align center/middle with the rest of the elements. The elements include an image, paragraph text and CTA. Ideally all elements should vertically align in the middle

The CTA seems to have a larger bounding box than needed and the extra height of the bounding box seems to come from the rh-cta component shadow styles in the span. I notice when I inspect the individual elements in the CTA component they are not as high as the container surrounding the link and the arrow icon. 

### Which Component?

rh-cta

### Steps to reproduce

1. Go to this [preview link](https://www.redhat.com/en/solutions/automotive?at_preview_token=8IYpsM3UBv98Oyve4Xro_A&at_preview_index=1_1&at_preview_listed_activities_only=true) to view the example announcement personalization pattern. 
2. View the purple announcement band located below the hero image and above the picture of the car chassis.
3. Notice that the CTA is not centered with the first two items in the container (icon image and paragraph)

### Expected behaviour

On load the icon, paragraph and CTA in the announcement pattern should align vertically in the middle. 

### Screenshots

The rh-cta center line is below the center line of the other elements listed before the CTA.

![Screenshot 2024-06-13 at 10 08 23 AM](https://github.com/RedHat-UX/red-hat-design-system/assets/1126703/4f684a17-1b7e-47a7-8280-9f7b5cf73d27)

rh-cta has a total bounding box height of 28.8px

![Screenshot 2024-06-13 at 10 08 49 AM](https://github.com/RedHat-UX/red-hat-design-system/assets/1126703/b01c85c8-458c-43f3-8d3a-69d5a5378f2b)

However the two elements (CTA text and CTA icon) located inside the CTA container do not reach that height. They are shorter by 5.8px combined.

CTA text height 23px 

![Screenshot 2024-06-13 at 10 09 17 AM](https://github.com/RedHat-UX/red-hat-design-system/assets/1126703/517dcf02-81aa-4881-ae2f-8ca03d0f3281)

CTA icon height 13px

![Screenshot 2024-06-13 at 10 09 06 AM](https://github.com/RedHat-UX/red-hat-design-system/assets/1126703/bbfd2a1e-5686-4b74-bb3d-5abf4202b54c)

![Screenshot 2024-06-13 at 10 57 16 AM](https://github.com/RedHat-UX/red-hat-design-system/assets/1126703/8f308562-c742-463a-9c04-7a97e216f0f9)

### Element HTML

```HTML
<rh-surface class="rh-target-pzn1121400" color-palette="dark">
            <section class="dx-bg-dark-purple dx-text-white dx-py-2">
                <div class="dx-container">
                    <div class="dx-row dx-flex dx-justify-center dx-items-start md:dx-items-center">
                        <div class="dx-col-auto dx-text-right dx-pr-0">
                            <img width="48" height="48" src="https://www.redhat.com/rhdc/managed-files/red-hat-openshift-virtualization_full-color.svg" alt="">
                        </div>    
                        <div class="dx-col-10 sm:dx-col-auto lg:dx-flex dx-items-center">
                            <p class="dx-pr-3 dx-m-0">Manage VMs with Red&nbsp;Hat® OpenShift® Service on AWS.</p>
                            <rh-cta>
                                <a href="https://cloud.redhat.com/learn/how-manage-virtual-machines-using-red-hat-openshift-virtualization-red-hat-openshift-service?percmp=7015Y00000486qQQAQ" data-analytics-state="personalized||RH|Blog|OpenShift Virtualization - ROSA user" data-analytics-category="RH|Blog|Side panel|OpenShift Virtualization - ROSA user" data-analytics-text="Start the learning path" data-analytics-linktype="cta">Start the learning path</a>
                            </rh-cta>
                        </div>
                    </div>
                </div>
            </section>
        </rh-surface>
```

### Operating System (OS)

macOS

### Browser

Chrome

### Additional Info

The personalization patterns use rh design system along with [DX utilities found here](https://uxdd.pages.corp.redhat.com/dx-utilities/utilities/typography/).

**Comment by markcaron** [comment]
@dustinmazon looking into this...

The `line-height` for both the `<p>` and `<rh-cta>` are the same (i.e., `24px`), so their bounding box size is identical. With the DX Utils applied (i.e., `lg:dx-flex dx-items-center`) they vertically align to the center as expected. So, I wouldn't say this is a bug in `<rh-cta>`.

I believe the real issue is that `<rh-cta>` has a `font-size: 18px` while the paragraph is `16px`, which would affect the baseline alignment. They're aligned properly based on their `line-heights`, but `18px` sits differently across the `1.5em` than `16px`, which is why you're seeing the slightly lower alignment (by ~1px).

<img width="845" alt="Screenshot 2024-06-27 at 9 30 57 AM" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/cf5805e6-00ec-40ab-aa1a-b7c91a34cf45">

Changing the `flex` alignment to `baseline` doesn't seem to fix the issue (unless I'm missing something), but there are a few solutions:

1. Change the paragraph size to `18px` to match `<rh-cta>`
2. Use the available CSS shadow part to adjust the font-size of `<rh-cta>` for that instance down to `16px`
3. Use the CSS custom property available for the `<rh-cta>` to adjust the font-size for that instance down to `16px`

### Option 1

I believe this would be the preferred option, since it's bringing the marketing text up to the size that matches the CTA, but I could be wrong.

Either way, the HTML / utility classes would look like:

```
<p class="dx-pr-3 dx-m-0 dx-text-14 sm:dx-text-18">
  Manage VMs with Red&nbsp;Hat® OpenShift® Service on AWS.
</p>
```

### Option 2

The CSS would look like:

```
rh-cta::part(container) {
  font-size: 16px;
}
```

### Option 3

The HTML with an inline style would look like:

```
<rh-cta style="--rh-font-size-body-text-lg: 16px;">
  ...
</rh-cta>
```

### Wrap up

This might also be a discussion with @coreyvickery and @marionnegp about what we want to do about the default `font-size` of `<rh-cta>` or how we want to document its usage when put inline with text like this announcement banner.

- Do we recommend that all text that's sitting inline with the CTA is `18px`?
- Or are we ok with make CTA look smaller (e.g., `16px`) which would make it inconsistent with other instances of CTA?


Hopefully all of that made sense. Happy to discuss futher.

**Comment by coreyvickery** [comment]
Always change body text size, not alter components.

**Comment by markcaron** [comment]
Thanks, @coreyvickery 

@dustinmazon, so it seems like the design of the announcement banner will need to bump up the font-size to be consistent with the CTA.

On the developer side, this is super easy using the DX Utils like my Option 1 above.

Going to close this issue, but we can always discuss further if needed.
