### ISSUE TITLE
Logo Wall: responsive design

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#1782]
> It seems like there might be a bug for [1x1, 1x1 flat]. At about 1200px to 1520px, the content breaks out of the container.

_Originally posted by @gradymcgee in https://github.com/RedHat-UX/red-hat-design-system/pull/1772#discussion_r1728010245_

**Comment by bennypowers** [comment]
I could reproduce this in chrome, but not in firefox. At first it seemed like it might be a layout issue with `<uxdot-pattern>`, but I tried replacing that element with just the pattern code, and it looks like indeed the non-wrapping examples do break out of their container when the content is too wide for it.

**Comment by adamjohnson** [comment]
It looks like this is because lines 99 and 111 define the `container-name` as `host`; however, `container-name: host;` is never explicitly set. So, those rules aren't getting applied.

`flex-wrap: wrap;` is being applied inside these `@container` queries. `flex-wrap: wrap;` does indeed help the layout.

I also see this layout issue in Edge but Firefox displays it as it should.

There may be some work to do here around using only `@media` or `@container` as well.

**Comment by diwanshi** [comment]
@bennypowers thanks i'll take a look at this.
@adamjohnson i might need some help here, by container-name host i was referring to uxdot-pattern's container name.
