### ISSUE TITLE
[bug] `*-lightdom.css` contains unpopulated css variables with no fallbacks

### ISSUE THREAD

**Issue by zhawkins** [RedHat-UX/red-hat-design-system#1955]
### Describe the bug

Multiple lightdom css files seem to be missing css variable fallbacks. That means these light DOM styles aren't doing a whole lot until JS boots up. It'd be great if they could have some sort of defaults set.

`rh-tile-lightdom.css`

contains

```
rh-tile a {
  color: var(--_link-color) !important;
  text-decoration: var(--rh-tile-link-text-decoration, none) !important;
}
```

There's no fallback for `--_link-color` so it's just empty.

Same with `rh-breadcrumb-lightdom.css`

```
rh-breadcrumb > ol > li {
  background-image: var(--_breadcrumb-caret-image-default);
```

Discussed here: https://redhat-internal.slack.com/archives/C0686DG8YSJ/p1727897987897609

### Steps to reproduce

`rh-tile-lightdom.css`

contains

```
rh-tile a {
  color: var(--_link-color) !important;
  text-decoration: var(--rh-tile-link-text-decoration, none) !important;
}
```

### Expected behaviour

There is a default value provided for css variables that aren't populated within lightDOM styles.

### Operating System (OS)

Windows

### Browser

Microsoft Edge

**Comment by markcaron** [comment]
I believe there's some confusion around the purpose of that `rh-tile-lightdom.css` file. The intended purpose is for styling deeply nested elements, not for shimming `:not-defined()` styles. So, it's working exactly as intended, since at the time of hydration, those vars will be set.

If you're looking for a `rh-tile-lightdom-shim.css` file, then we can discuss that as a separate file and issue.
