### ISSUE TITLE
[docs][bug] Logo Wall Examples missing styles 

### ISSUE THREAD

**Issue by adamjohnson** [RedHat-UX/red-hat-design-system#1979]
### Description

If you visit the Logo Wall Examples page, you'll notice gigantic logos.

### Screenshots

![Logo Wall pattern examples with giant logos](https://github.com/user-attachments/assets/5f5596bc-cad2-4904-93b5-8dbd62699efc)

### Steps to reproduce

1. Visit the [Logo Wall Examples](https://ux.redhat.com/patterns/logo-wall/examples/) page.
2. Observe the broken layout and gigantic logos

### Expected behaviour

The Logo Wall examples should look like the [Sample Patterns](https://ux.redhat.com/patterns/logo-wall/#sample-patterns) on the Overview page.

### Operating System (OS)

macOS

### Browser

Safari, Microsoft Edge

### Additional browser or assistive technology info

Console shows the logo-wall-lightdom.css file is not loading and likely causing these issues.

**Comment by zeroedin** [comment]
Will be fixed when #1953 merges

https://deploy-preview-1953--red-hat-design-system.netlify.app/patterns/logo-wall/examples/ 

I included a change to the 11ty config there for a seperate reason in that PR, the desire to use CSS/JS in the sub folders of `/docs` directory.  In doing so it fixes the issue here as well as `uxdot-pattern` is looking for a file in sub directories as well and 11ty was not copying those over to `_site/*` on build
