### ISSUE TITLE
[bug] Install / import issues

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#295]
### Describe the bug

There are a few issues I ran into trying to use the `@rhds/elements` npm package.

## Unpkg duplicate pfe-icon issue

Using the `?module` flag when importing `rh-footer`

```js
import "https://unpkg.com/@rhds/elements@1.0.0-beta.3/elements/rh-footer/rh-footer.js?module";
```

Result:

![Screen Shot 2022-05-19 at 3 58 22 PM](https://user-images.githubusercontent.com/3428964/169396578-50f08d7a-33be-4d82-9646-4f84bb358e1d.png)

Example:

https://codepen.io/heyMP/pen/mdXmzqV?editors=1010

## [fixed] <s>Npm install fails on post install script</s>

When installing the `@rhds/elements` package npm throws the following error:

```bash
npm install @rhds/elements@1.0.0-beta.3
```

Result: 

```bash
npm ERR! code 1
npm ERR! path /Users/michael/Projects/rh-footer-demo/node_modules/@rhds/elements
npm ERR! command failed
npm ERR! command sh -c run-s postinstall:**
npm ERR! > @rhds/elements@1.0.0-beta.3 postinstall:patch
npm ERR! > patch-package
npm ERR!
npm ERR! patch-package 6.4.7
npm ERR! Applying patches...
npm ERR!
npm ERR! > @rhds/elements@1.0.0-beta.3 postinstall:husky
npm ERR! > npx husky install
npm ERR! No patch files found
npm ERR! husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/michael/Projects/rh-footer-demo/node_modules/@rhds/elements
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c npx husky install
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/michael/.npm/_logs/2022-05-19T20_32_00_605Z-debug.log
npm ERR! ERROR: "postinstall:husky" exited with 1.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michael/.npm/_logs/2022-05-19T20_32_02_874Z-debug.log
```

**Comment by bennypowers** [comment]
Not quite sure yet what the problem is on codepen, but

https://lit.dev/playground/#project=W3sibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9lbGVtZW50cy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxyaC1mb290ZXI-PC9yaC1mb290ZXI-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX0seyJuYW1lIjoiZWxlbWVudHMudHMiLCJjb250ZW50IjoiaW1wb3J0ICdAcmhkcy9lbGVtZW50cyc7XG4gICJ9XQ

**Comment by bennypowers** [comment]
@heyMP https://codepen.io/bennyp/pen/NWygKOa

**Comment by heyMP** [comment]
Ahhh nice!  If it's just an unpkg issue.

Updated demo with jspm: https://codepen.io/heyMP/pen/LYQLEzd
