### ISSUE TITLE
[feat]: <rh-timestamp> ready to migrate

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#548]
### Tag Name

pfe-timestamp

### RHDS Only

- [ ] The component will be **RHDS only**, delete the PFE component once published

### Additional Info

PFE Timestamp has already been updated in PF 1:1. We now need an `<rh-timestamp>` component for RHDS. No design tweaks necessary.

**Comment by markcaron** [comment]
@kylebuch8, I believe @zhawkins had an idea for timezone implementation. Can you sync up with him as you tackle this component?

**Comment by bennypowers** [comment]
[`Intl.DateTimeFormat()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) does a lot of the heavy lifting for us and comes with the browser.

**Comment by eyevana** [comment]
@markcaron confused by the bullet point in the description that says RHDS only...we're still keeping pf-timestamp, right? I do see [PF4](https://www.patternfly.org/v4/components/timestamp) has it as well, although it's a beta feature. If we're keeping in both libraries, should I explore using controllers instead of creating a base class/extending and all that jazz @bennypowers? If there's anything else I need to tackle as part of the feature, let me know.

**Comment by bennypowers** [comment]
yeah if you can abstract out the computation parts to a controller that'd let us ship both without extending

**Comment by bennypowers** [comment]
Timestamp controller went out with [pfe-core 2.4.0](https://github.com/patternfly/patternfly-elements/releases/tag/%40patternfly%2Fpfe-core%402.4.0)

**Comment by coreyvickery** [comment]
@hellogreg Do we need a separate docs issue or should we add the docs work to this issue?

**Comment by bennypowers** [comment]
In the previous releases we had separate issues for things like docs, design, and dev. while there are advantages to that, it could also be the case that separating issues out by role led to some confusion and ultimately cramming for the release. Could we try a more holistic approach to tracking that treats docs, design, accessibility and dev as parts of a whole rather than isolated, independent tasks?

**Comment by hellogreg** [comment]
@coreyvickery I agree with @bennypowers. Let's try keeping the docs issue here.

**Comment by coreyvickery** [comment]
@eyevana Ready for you.

XD: https://xd.adobe.com/view/a749fc5b-c52f-4a97-beae-30e655c89bb6-f21a/
Content doc: https://docs.google.com/document/d/1o0XUMKqez5bt4u7dtGlLIfL-m9IXuMyYUislYqgHSX4/edit
Images: https://www.dropbox.com/sh/a8esxfydh50rhx6/AAAZzIxlqtvHGfuCQsREkv3Ua?dl=0

**Comment by eyevana** [comment]
@coreyvickery Can you provide the image and summary for the elements page, please?

**Comment by coreyvickery** [comment]
@eyevana Done, check your alerts.
