### ISSUE TITLE
[bug] Cannot read properties of undefined (reading 'invoker') floating-com-controller.js

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#701]
## Description of the issue

We're seeing an error with the `floating-dom-controller` on sites that are using the latest version of rh-tooltip.

`@rhds/elements@1.0.0-beta.27`

### Which Component?

rh-tooltip

### Steps to reproduce

1. Go to https://deploy-preview-55--red-hat-design-tokens.netlify.app/
2. Open console and see the following error

![Screenshot 2023-01-12 at 12 21 05 PM](https://user-images.githubusercontent.com/3428964/212135835-f60e788c-6200-4708-98be-1213376aac33.png)

**Comment by bennypowers** [comment]
we have this same problem on the [tokens site](https://deploy-preview-55--red-hat-design-tokens.netlify.app/)

can you take a look @brianferry ?

**Comment by brianferry** [comment]
Sure thing @bennypowers

**Comment by brianferry** [comment]
I'm thinking this is caused by pfe-core being published with the `floating-ui` floating-dom-controller but the version of rh-tooltip with it updated to the new library has not yet being published.  

Version Beta.27 of the tooltip still uses popper but Beta.28 does not, my demo here https://codepen.io/OhHeyBrian/pen/dyjRbWz shows Beta.27 working with Popper and 1 version back on pfe-core being used.

JSPM is bringing in the latest version of core automatically so while it is bringing in the `floating-ui` libraries it does not have the latest code that uses it for tooltip yet.

**Comment by bennypowers** [comment]
JSPM has a way to specify fixes for versions broken this way

https://github.com/jspm/overrides

If we publish and update all the dependencies, that should fix the next version

**Comment by heyMP** [comment]
Added this to our wiki: https://github.com/RedHat-UX/red-hat-design-system/wiki/JSPM
