### ISSUE TITLE
Investigate lightDOM style construction for use outside of JS module as a simple Custom Element

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#899]
We'll need to figure out a way to construct a separate lightDOM stylesheet for certain components that consumers may want as Custom Elements only (no JavaScript).

For example, RH CTA could be used as a Custom Element and styled with lightDOM without needing `rh-cta.js`.

**Comment by bennypowers** [comment]
Declarative Shadow DOM is the standards-based way to do this.

Ideally, by [the time Firefox ships DSD](https://bugzilla.mozilla.org/show_bug.cgi?id=1712140), we should recommend DSD-first implementations, instead of light-DOM sheets, and only use light-DOM sheets for things like styling nested slotted elements.
