### ISSUE TITLE
[docs] Font weight of inline alert titles on UX dot

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#920]
The live ux.redhat.com shows the right font weight for the heading/title:
<img width="1071" alt="Screenshot 2023-04-13 at 11 52 48 AM" src="https://user-images.githubusercontent.com/95588923/231822656-3bc4022a-6823-4642-bb0c-64a7ca654fb2.png">

But deploy and local previews are showing it at a font weight of 400, which is what other headings are using on ux dot:
<img width="1074" alt="Screenshot 2023-04-13 at 12 00 05 PM" src="https://user-images.githubusercontent.com/95588923/231822796-b9e347e2-91ff-46ed-a4c9-09fcd3cf008f.png">

I'm not sure if this resolves itself once PRs are merged and are live.

**Comment by coreyvickery** [comment]
Changing the font weight to `600` seems to fix it, but it makes the headings thicker, so I'm not sure what the fix is here.

Also, the icon is also sitting a bit too low and there is too much bottom padding. Specs are below.

https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/84de1e95-5aca-4782-8eba-5a98804f93a6/specs/
